version: '3'
services:

  mongodb:
    image: "mongo:4.0.7"
    container_name: "chat-mongodb"
    # ports:
    #   - "27017:27017"
    # volumes:
    #   - ./mongodb:/data/db

  web:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - "mongodb"
    ports:
      - "3000:3000"

